_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: f1f552bc-2ca1-4b0a-b0aa-1457d4256622
name: 'Task 1'
mail: juancaom12@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/9
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
